import { NextPage } from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import HomeContainer from './home/index'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>GMD-22</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:wght@300&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className={styles.main}>
        <HomeContainer />
      </main>
    </div>
  )
}

export default Home
